jobs:
  run-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Run 'pre-commit' hooks
        uses: dycw/action-pre-commit@latest
        with:
          repos: |-
            pre-commit/pre-commit-hooks
          hooks: |-
            nitpick
name: pull-request
"on":
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
